# Generated by Django 4.2.7 on 2026-01-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('code', models.CharField(max_length=6, verbose_name='인증코드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('is_verified', models.BooleanField(default=False, verbose_name='인증완료여부')),
            ],
            options={
                'verbose_name': '이메일 인증',
                'verbose_name_plural': '이메일 인증',
                'ordering': ['-created_at'],
            },
        ),
    ]
