# Generated by Django 4.2.7 on 2026-01-07 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('breed', models.CharField(max_length=100, verbose_name='종')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='체중(kg)')),
                ('gender', models.CharField(choices=[('male', '수컷'), ('female', '암컷')], max_length=10, verbose_name='성별')),
                ('neutered', models.CharField(choices=[('yes', '중성화 함'), ('no', '중성화 안 함'), ('unknown', '모름')], max_length=10, verbose_name='중성화 여부')),
                ('diseases', models.TextField(blank=True, null=True, verbose_name='기저질환')),
                ('medications', models.TextField(blank=True, null=True, verbose_name='복용 중인 약')),
                ('allergies', models.TextField(blank=True, null=True, verbose_name='알레르기')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='소유자')),
            ],
            options={
                'verbose_name': '반려견',
                'verbose_name_plural': '반려견',
                'ordering': ['-created_at'],
            },
        ),
    ]
